### PR TITLE
Untested Workflow mockup.

### PR DESCRIPTION
**Pull request by eriksimonic**
I have created some files interfaces to implement a workflow functionality.
I am really new to Angular so I didn't try to make any changes to the backend..

I did create a PluginController, with a method GetAllAvalableWorkflows. That returns a list of WorkflowInfo.

I did add a workflow executer in the Collect.. methos.

So if you have time check it out.. it may be a good thing to implement. 

Regards!

PS Auto merge is laying. :)

### CODE REVIEW

**Comment by kjac** [comment]
Hi @eriksimonic,

Interesting. And thank you. I'll give it a closer look when I find the time. From the looks of it, I do fear it gets a little complex for devs in terms of extending the back office. But I'll give it some thought for sure. 

You do know about the Form Editor events, right? Otherwise you can read about them [here](https://github.com/kjac/FormEditor/blob/master/Docs/extend.md). For the time being those are used for custom workflow extensions. You could configure your workflows on the content item that contains the form using standard Umbraco functionality. Hava a look at this code sample:

```cs
using System.Web;
using FormEditor;
using FormEditor.Events;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace Site.FormEditor
{
	public class FormEditorEvents : ApplicationEventHandler
	{
		protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
		{
			FormModel.BeforeAddToIndex += FormModelOnBeforeAddToIndex;
			FormModel.AfterAddToIndex += FormModelOnAfterAddToIndex;
		}

		private void FormModelOnBeforeAddToIndex(FormModel sender, FormEditorCancelEventArgs formEditorCancelEventArgs)
		{
			var requestedContent = GetRequestedContent();
			if(requestedContent == null)
			{
				return;
			}

			if(requestedContent.GetPropertyValue<bool>("FormEditor_Workflow_DoThisThing"))
			{
				// do this thing before the form submission is added to the index
			}
		}

		private void FormModelOnAfterAddToIndex(FormModel sender, FormEditorEventArgs formEditorEventArgs)
		{
			var requestedContent = GetRequestedContent();
			if(requestedContent == null)
			{
				return;
			}

			if(requestedContent.GetPropertyValue<bool>("FormEditor_Workflow_DoThatThing"))
			{
				// do that thing after the form submission is added to the index
			}
		}

		private IPublishedContent GetRequestedContent()
		{
			if(UmbracoContext.Current.IsFrontEndUmbracoRequest)
			{
				return UmbracoContext.Current.PublishedContentRequest.PublishedContent;
			}
			var id = HttpContext.Current.Request.Form["_id"];
			int contentId;
			if(id != null && int.TryParse(id, out contentId))
			{
				return UmbracoContext.Current.ContentCache.GetById(contentId);
			}
			return null;
		}
	}
}
```

**Comment by eriksimonic** [comment]
Yes I checked the event, and I thought of this approach to.. 
but it would make sense to have this integrated in the property editor.

I don't think that the implementation is much complicated, as you need to create an class that extends FromWorkflow... nad implement the action you would like to accomplish.. that's all. Very similar haw you implement an workflow in a MS CRM 
basically not much more complicated as creating custom validation or something else :)

For the time being, I will implement the functionality as suggested.
Thank you for a great FormEditor.

**Comment by eriksimonic** [comment]
@kjac 

I did implement the change, but the approach is unusable when used in a Macro. AsFormModel does not expose IPuclishedContent

**Comment by kjac** [comment]
Hmmm I actually had a feeling you might encounter that issue. I'll see what I can do about it, probably add the content ID or the content itself to the event args.

I'm releasing a new version tomorrow (probably) so it'll get to this shortly thereafter.

**Comment by eriksimonic** [comment]
I did create a patch to address this issue. Just check and if it is ok marge and release :) 
EventArgs wont do it as all other methods will fail .. basically the FromModel is unusable as only the collectdata is using a predefined IPucshedContent, my fix I think fixes this.

**Comment by kjac** [comment]
Closing this for now. Maybe there will be time to pick this up in the future, if more people request it.

**Pull request closed without merging**
